/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        outline: '#849495',
        'surface-container-high': '#2a2a2a',
        'tertiary-fixed-dim': '#eac324',
        'surface-container-low': '#1c1b1b',
        'outline-variant': '#3b494b',
        'on-secondary-fixed-variant': '#474746',
        'surface-container': '#201f1f',
        'on-tertiary': '#3b2f00',
        'on-secondary': '#313030',
        'primary-fixed-dim': '#00dbe9',
        'on-secondary-container': '#b7b5b4',
        background: '#131313',
        'on-tertiary-fixed': '#231b00',
        'tertiary-fixed': '#ffe179',
        'on-background': '#e5e2e1',
        'surface-container-highest': '#353534',
        'on-tertiary-fixed-variant': '#554500',
        error: '#ffb4ab',
        'primary-fixed': '#7df4ff',
        'on-tertiary-container': '#715d00',
        'surface-tint': '#00dbe9',
        'on-surface-variant': '#b9cacb',
        'on-primary-container': '#006970',
        'on-primary-fixed-variant': '#004f54',
        'on-primary': '#00363a',
        'inverse-surface': '#e5e2e1',
        primary: '#dbfcff',
        'error-container': '#93000a',
        'surface-variant': '#353534',
        'on-secondary-fixed': '#1c1b1b',
        'on-error-container': '#ffdad6',
        'surface-dim': '#131313',
        'inverse-on-surface': '#313030',
        'secondary-fixed-dim': '#c8c6c5',
        tertiary: '#fff5de',
        'secondary-container': '#474746',
        'on-surface': '#e5e2e1',
        'on-primary-fixed': '#002022',
        'surface-container-lowest': '#0e0e0e',
        'tertiary-container': '#fed639',
        'inverse-primary': '#006970',
        secondary: '#c8c6c5',
        'secondary-fixed': '#e5e2e1',
        'on-error': '#690005',
        'primary-container': '#00f0ff',
        surface: '#131313',
        'surface-bright': '#3a3939',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'container-max': '1200px',
        unit: '8px',
        gutter: '24px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'body-md': ['Geist', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
